name: Build, Upload, and Sync

on:
  workflow_dispatch:
  push:
    branches:
      - main  # 监听 main 分支的推送
  pull_request:
    branches:
      - main  # 监听 main 分支的拉取请求

jobs:
  build-and-sync:
    runs-on: ubuntu-latest

    steps:
      # 设置时区为亚洲/上海
      - name: Set Timezone to Asia/Shanghai
        run: |
          sudo timedatectl set-timezone Asia/Shanghai
          echo "Current time: $(date)"

      # 检出代码
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 缓存 Gradle
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # 设置 JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      # 赋予 Gradlew 执行权限
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 同时编译 Normal 和 Compatible APK
      - name: Build Normal and Compatible APKs
        run: |
          ./gradlew assembleNormalRelease assembleCompatibleRelease -Pversion=${{ github.ref_name }}

      # 签名 Normal APK
      - name: Sign Normal APK
        id: sign_normal_apk
        uses: ilharp/sign-android-release@v1
        with:
          releaseDir: app/build/outputs/apk/normal/release/
          signingKey: ${{ secrets.ANDROID_SIGNING_KEY }}
          keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
          buildToolsVersion: 31.0.0

      # 签名 Compatible APK
      - name: Sign Compatible APK
        id: sign_compatible_apk
        uses: ilharp/sign-android-release@v1
        with:
          releaseDir: app/build/outputs/apk/compatible/release/
          signingKey: ${{ secrets.ANDROID_SIGNING_KEY }}
          keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
          buildToolsVersion: 31.0.0

      # 创建新的 Release 标签
      - name: Create new release tag
        id: create_release_tag
        run: |
          echo "Creating new release tag..."
          NEW_TAG="v${{ github.ref_name }}-${{ github.run_id }}"
          git tag $NEW_TAG
          git push origin $NEW_TAG
          echo "::set-output name=new_tag::$NEW_TAG"

      # 上传 Normal APK 到新的 Release
      - name: Upload Normal APK to New Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ steps.sign_normal_apk.outputs.signedFile }}
          draft: false
          prerelease: false
          tag_name: ${{ steps.create_release_tag.outputs.new_tag }}
          name: Sesame-Normal-${{ steps.create_release_tag.outputs.new_tag }}
          body: |
            Sesame-Normal-${{ steps.create_release_tag.outputs.new_tag }} Release

            **更新内容**:
            ${{ github.event.release.body || '无更新说明' }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          target_commitish: ${{ github.sha }}

      # 上传 Compatible APK 到新的 Release
      - name: Upload Compatible APK to New Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ steps.sign_compatible_apk.outputs.signedFile }}
          draft: false
          prerelease: false
          tag_name: ${{ steps.create_release_tag.outputs.new_tag }}
          name: Sesame-Compatible-${{ steps.create_release_tag.outputs.new_tag }}
          body: |
            Sesame-Compatible-${{ steps.create_release_tag.outputs.new_tag }} Release

            **更新内容**:
            ${{ github.event.release.body || '无更新说明' }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          target_commitish: ${{ github.sha }}


      #   # 同步 Release 到目标仓库
      # - name: Sync Release to Target Repository
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     files: |
      #       ${{ steps.sign_normal_apk.outputs.signedFile }}
      #       ${{ steps.sign_compatible_apk.outputs.signedFile }}
      #     token: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # 使用具有写入目标仓库权限的PAT
      #     tag_name: ${{ github.ref_name }}
      #     release_name: Release ${{ github.ref_name }}
      #     draft: false
      #     prerelease: false
      #     body: |
      #       本 Release 同步自源仓库 [Sesame-TK](https://github.com/${{ github.repository }})
            
      #       **更新内容**:
      #       ${{ github.event.release.body || '无更新说明' }}
      #   env:
      #     GITHUB_REPOSITORY: 'Xposed-Modules-Repo/fansirsqi.xposed.sesame' # 目标仓库的拥有者和仓库名称
