name: Build, Upload, and Sync

on:
  release:
    types: [ published ] # 自动触发同步

jobs:
  build-and-sync:
    runs-on: ubuntu-latest

    steps:
      # 设置时区为亚洲/上海
      - name: Set Timezone to Asia/Shanghai
        run: |
          sudo timedatectl set-timezone Asia/Shanghai
          echo "Current time: $(date)"

      # 检出代码
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 缓存 Gradle
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # 设置 JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      # 赋予 Gradlew 执行权限
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 同时编译 Normal 和 Compatible APK
      - name: Build Normal and Compatible APKs
        run: |
          ./gradlew assembleNormalRelease assembleCompatibleRelease -Pversion=${{ github.ref_name }}

      # 签名 Normal APK
      - name: Sign Normal APK
        id: sign_normal_apk
        uses: ilharp/sign-android-release@v1
        with:
          releaseDir: app/build/outputs/apk/normal/release/
          signingKey: ${{ secrets.ANDROID_SIGNING_KEY }}
          keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
#          buildToolsVersion: 31.0.0

      # 签名 Compatible APK
      - name: Sign Compatible APK
        id: sign_compatible_apk
        uses: ilharp/sign-android-release@v1
        with:
          releaseDir: app/build/outputs/apk/compatible/release/
          signingKey: ${{ secrets.ANDROID_SIGNING_KEY }}
          keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
#          buildToolsVersion: 31.0.0

        # 上传 Normal APK 到当前仓库 Release
      - name: Upload Normal APK to Source Release
        uses: termux/upload-release-action@v4.2.0
        with:
          asset_name: Sesame-Normal-${{ github.event.release.tag_name || github.ref_name }}.apk
          file: ${{ steps.sign_normal_apk.outputs.signedFile }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          overwrite: true
          checksums: sha256
          checksums_file_name: CHECKSUMS-Sesame-Normal-${{ github.event.release.tag_name || github.ref_name }}.%algo%

      # 上传 Compatible APK 到当前仓库 Release
      - name: Upload Compatible APK to Source Release
        uses: termux/upload-release-action@v4.2.0
        with:
          asset_name: Sesame-Compatible-${{ github.event.release.tag_name || github.ref_name }}.apk
          file: ${{ steps.sign_compatible_apk.outputs.signedFile }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          overwrite: true
          checksums: sha256
          checksums_file_name: CHECKSUMS-Sesame-Compatible-${{ github.event.release.tag_name || github.ref_name }}.%algo%


        # 同步 Release 到目标仓库
      - name: Sync Release to Target Repository
        uses: softprops/action-gh-release@v2
        with:
          repository: Xposed-Modules-Repo/fansirsqi.xposed.sesame # 目标仓库的拥有者和仓库名称
          nanme: Sesame-${{ github.event.release.tag_name || github.ref_name }} # 发布的名称。默认为标签名称
          files: |
            ${{ steps.sign_normal_apk.outputs.signedFile }}
            ${{ steps.sign_compatible_apk.outputs.signedFile }}
          token: ${{ secrets.TARGET_REPO_PAT }} # 使用具有写入目标仓库权限的PAT
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false #指示此版本是否为草稿
          prerelease: false #是否为预发行
          append_body: true #是否将源仓库 Release 内容附加到此版本
          make_latest: true #是否将此版本设为最新版本
          body: | #传达此版本中显著变化的文本
            本 Release 同步自源仓库 [Sesame-TK](https://github.com/${{ github.repository }})
            **更新内容**:
            ${{ github.event.release.body || '无更新说明' }}
