name: Build & Upload Apk To Release

on:
  workflow_dispatch:
  push:
    branches:
      - main  # 监听 main 分支的推送
  pull_request:
    branches:
      - main  # 监听 main 分支的拉取请求
jobs:
  build-and-sync:
    runs-on: ubuntu-latest

    steps:
      # 设置时区为亚洲/上海
      - name: Set Timezone to Asia/Shanghai
        run: |
          sudo timedatectl set-timezone Asia/Shanghai
          echo "Current time: $(date)"

      # 检出代码
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 缓存 Gradle
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # 设置 JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      # 赋予 Gradlew 执行权限
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 同时编译 Normal 和 Compatible APK
      - name: Build Normal and Compatible APKs
        run: |
          ./gradlew assembleNormalRelease assembleCompatibleRelease -Pversion=${{ github.ref_name }}

      # 签名 Normal APK
      - name: Sign Normal APK
        id: sign_normal_apk
        uses: ilharp/sign-android-release@v1
        with:
          releaseDir: app/build/outputs/apk/normal/release/
          signingKey: ${{ secrets.ANDROID_SIGNING_KEY }}
          keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
          buildToolsVersion: 31.0.0

      # 签名 Compatible APK
      - name: Sign Compatible APK
        id: sign_compatible_apk
        uses: ilharp/sign-android-release@v1
        with:
          releaseDir: app/build/outputs/apk/compatible/release/
          signingKey: ${{ secrets.ANDROID_SIGNING_KEY }}
          keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
          buildToolsVersion: 31.0.0

      # 上传 Normal APK 到当前仓库 Release
      - name: Upload Normal APK to Source Release
        uses: termux/upload-release-action@v4.2.0
        with:
          asset_name: Sesame-Normal-${{ github.event.release.tag_name || github.ref_name }}.apk
          file: ${{ steps.sign_normal_apk.outputs.signedFile }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          overwrite: true
          checksums: sha256
          checksums_file_name: CHECKSUMS-Sesame-Normal-${{ github.event.release.tag_name || github.ref_name }}.%algo%

      # 上传 Compatible APK 到当前仓库 Release
      - name: Upload Compatible APK to Source Release
        uses: termux/upload-release-action@v4.2.0
        with:
          asset_name: Sesame-Compatible-${{ github.event.release.tag_name || github.ref_name }}.apk
          file: ${{ steps.sign_compatible_apk.outputs.signedFile }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          overwrite: true
          checksums: sha256
          checksums_file_name: CHECKSUMS-Sesame-Compatible-${{ github.event.release.tag_name || github.ref_name }}.%algo%

      # 同步 Release 到目标仓库
      # - name: Sync Release to Target Repository
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     files: |
      #       ${{ steps.sign_normal_apk.outputs.signedFile }}
      #       ${{ steps.sign_compatible_apk.outputs.signedFile }}
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     tag_name: ${{ github.ref_name }}
      #     repository: Xposed-Modules-Repo/fansirsqi.xposed.sesame # 指定目标仓库
      #     body: |
      #       本 Release 同步自源仓库 [Sesame-TK](https://github.com/${{ github.repository }})

      #       **更新内容**:
      #       ${{ github.event.release.body || '无更新说明' }}
